# -*- encoding=utf8 -*-
__author__ = "aijinka"

from airtest.core.api import *
from poco.drivers.ios import iosPoco
auto_setup(__file__)
connect_device("ios:///127.0.0.1:8100")
poco = iosPoco()
sleep(1.0)

#if  poco(rect="{'y': 204, 'x': 91, 'width': 203, 'height': 25}").exists():
 #   poco(rect="{'y': 204, 'x': 91, 'width': 203, 'height': 25}").click()

#else:
 #   print("xxxxxxx")
touch([91,204])
sleep(2)
print(poco.dump())
sleep(2)
poco(text="t").click()
poco("t").click()
poco("e").click()
poco("s").click()
poco("t").click()
poco("e").click()
poco("r").click()
poco("3").click()
poco("5").click()
poco("0").click()
touch([91,297])
sleep(2)
print(poco.dump())
poco("A").click()
poco("a").click()
poco("1").click()
poco("2").click()
poco("3").click()
poco("4").click()
poco("5").click()
poco("6").click()
poco(rect="{'y': 402, 'x': 167, 'width': 41, 'height': 22}").click()

sleep(2.0)
poco(text="儲值").click()
sleep(2.0)
poco(text="現金儲值").click()
poco("tw.com.icash.a.icashpay.debuging:id/add_100").click()
poco("tw.com.icash.a.icashpay.debuging:id/text").click()
poco("tw.com.icash.a.icashpay.debuging:id/title_left").click()
poco("tw.com.icash.a.icashpay.debuging:id/title_right").click()
poco(text="自帶杯儲值").click()
sleep(1.0)

poco("tw.com.icash.a.icashpay.debuging:id/close").click()
poco(text="中獎發票儲值").click()
sleep(1.0)

poco("tw.com.icash.a.icashpay.debuging:id/close").click()
poco("tw.com.icash.a.icashpay.debuging:id/title_right").click()
poco("tw.com.icash.a.icashpay.debuging:id/fund").click()
poco("tw.com.icash.a.icashpay.debuging:id/loan").click()
poco("tw.com.icash.a.icashpay.debuging:id/personal").click()
poco(text="交易限額").click()
sleep(1.0)

poco("tw.com.icash.a.icashpay.debuging:id/toolbarLeftArrow").click()
poco("tw.com.icash.a.icashpay.debuging:id/lvSetting").click()
sleep(1.0)
poco(text="授權扣款管理").click()
sleep(1.0)
poco("tw.com.icash.a.icashpay.debuging:id/toolbarLeftArrow").click()
sleep(1.0)

poco(text="使用教學").click()
sleep(1.0)

poco("tw.com.icash.a.icashpay.debuging:id/toolbarLeftArrow").click()
poco(text="版本與登入紀錄").click()
poco("tw.com.icash.a.icashpay.debuging:id/toolbarLeftArrow").click()
sleep(1.0)
poco(text="常見問題").click()
poco("tw.com.icash.a.icashpay.debuging:id/toolbarLeftArrow").click()
sleep(1.0)
poco(text="服務條款").click()
poco("tw.com.icash.a.icashpay.debuging:id/toolbarLeftArrow").click()
sleep(1.0)
poco(text="聯絡我們").click()
poco("tw.com.icash.a.icashpay.debuging:id/toolbarLeftArrow").click()
sleep(1.0)
poco("android.widget.ImageView").click()

poco("tw.com.icash.a.icashpay.debuging:id/barcode").click()
poco("tw.com.icash.a.icashpay.debuging:id/member_image").click()
poco("android.widget.ImageView").click()
poco(text="環球購物中心(僅環球點數)").click()
poco("tw.com.icash.a.icashpay.debuging:id/barcode").click()
sleep(1.0)
poco("tw.com.icash.a.icashpay.debuging:id/close").click()
poco("tw.com.icash.a.icashpay.debuging:id/close").click()
